springdoc:
  swagger-ui:
    tagsSorter: alpha

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/efrp_wealth_goals_app?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # "create", "update", "validate", or "none"
    show-sql: false

    properties:
      hibernate:
        format_sql: true
